### ISSUE TITLE
Bug in https://docs.neon-labs.org/ trying to access https://neonscan.org/ - URL

### ISSUE THREAD

**Issue by OnChainKevinn** [neonlabsorg/neon-support#1]
---
name: Bug Report
about: Describe an issue in the Neon EndToEnd suite
title: 'Bug in https://docs.neon-labs.org/ trying to access https://neonscan.org/ - URL'
labels: bug
assignees: ''"
---

**Bug Description**
When trying to access https://neonscan.org/ from https://docs.neon-labs.org/ the URL is not good.

**Steps to Reproduce**
1. Go to https://docs.neon-labs.org/
2. Click on Strat Developing dApps
3. In the left side, click "Using utilities"
4. Click NeonScan.
...

**Expected Behavior**
When clicking in the NeonScan, should open https://neonscan.org/ and NOT https://neonscan.%27org/

**Actual Behavior**
Opening https://neonscan.%27org/

-Image-
![image](https://user-images.githubusercontent.com/49716006/161984140-bb795612-6d6d-4590-99bc-21cdee80fb30.png)

**Comment by gigimon** [comment]
Hello! Link fixed, thx for Your report
