### ISSUE TITLE
Allowed negative value in the amount field

### ISSUE THREAD

**Issue by Chaouchinho** [neonlabsorg/neon-support#11]
**Bug Description**
It is possible to enter a négative value in the field

**Steps to Reproduce**
1.Go to https://neonpass.live/
2. From : Solana / To : Neon
3. Click on Connect Wallet
4. Click on select a token and select a token
5. Enter a negative value in the ammount field
6. Click on next
7. Click on next
...

**Actual Behavior**
![image](https://user-images.githubusercontent.com/103394869/162653929-2b3359fb-9439-419e-8893-b7bc0ee0e750.png)

**Comment by WebKieth** [comment]
It will be fixed by related issue, cause this is single mechanics
https://github.com/neonlabsorg/neon-support/issues/12

**Comment by gigimon** [comment]
Hello, Thank You for bug report. This problem was resolved, please check

**Comment by Chaouchinho** [comment]
Hello, thank you for fixing this bug.
It's fixed on my side.
