### ISSUE TITLE
Error in metamask when trying to send wei range amount

### ISSUE THREAD

**Issue by Chaouchinho** [neonlabsorg/neon-support#12]
**Bug Description**
A clear and concise description of the bug.

**Steps to Reproduce**
1.Go to https://neonpass.live/
2. From : Neon/ To : Solana
3. Click on Connect Wallet
4. Click on select a token and select a token
5. Enter "1e-18" in the ammount field
6. Click on next
7. Click on next
8. Validate the transaction in metamask

**Note that the fees taken from the account**

**Actual Behavior**
![image](https://user-images.githubusercontent.com/103394869/162654192-276511d1-b7b8-4b3e-91a3-22cfd65aec62.png)
![image](https://user-images.githubusercontent.com/103394869/162654244-8d05f7f9-e6c3-4ee2-be9e-aed6a8d3b939.png)

**Comment by Chaouchinho** [comment]
Hi the issue seem not be corrected in a good way.

You can not write 1e-18 but you still can past the string

![image](https://user-images.githubusercontent.com/103394869/162729250-0c2e57e3-99ad-43eb-bb25-7c88b2785219.png)

![image](https://user-images.githubusercontent.com/103394869/162729221-475e5fbe-b981-45e1-8255-cfbde1e64490.png)

**Comment by WebKieth** [comment]
https://github.com/neonlabsorg/neon-bridge-ui/pull/84

**Comment by Chaouchinho** [comment]
The issue is not fully corrected  
You can still put < 0.0000000000001 (1e-13 value in the amount field that is the min wei value for a transaction)

![image](https://user-images.githubusercontent.com/103394869/163067535-de731287-5c87-4732-8db9-f25fc55b300d.png)

**Comment by gigimon** [comment]
@Chaouchinho thx, we will recheck and fix this too
@WebKieth bump

**Comment by WebKieth** [comment]
new pull request contains regex pattern validation and dont fully block pasting to input

**Comment by gigimon** [comment]
@Chaouchinho hello, thank you for your report! We have fixed new cases, pelase check :)
