### ISSUE TITLE
Wrong period displayed for users on `Get tokens` page

### ISSUE THREAD

**Issue by s-medvedev** [neonlabsorg/neon-support#2]
**Bug Description**
is why don't we change text on our faucet saying "Next request will be unlock after 10 seconds expiration for a security reasons." to 60 seconds since it is 60 seconds?

**Steps to Reproduce**
1. Go to https://neonswap.live/#/get-tokens
2. Fill `Request test token`
3. Press `Get tokens`
4. Press `Get tokens` second time

**Expected Behavior**
Warning that tokens can be obtained after 60 seconds

**Actual Behavior**
A message with text: "Next request will be unlock after 10 seconds expiration for a security reasons."

**Comment by afalaleev** [comment]
Just to let you know that on Moraswap when you swap for example NEON to USDC first time it charged almost 2 NEON and later it is charging about 1 every time. So this is Moraswap, not Neonpass

**Comment by WebKieth** [comment]
Timer is still stay for one minute - I just fixed the locale
