### ISSUE TITLE
Token research works on a portion of the token adress

### ISSUE THREAD

**Issue by Chaouchinho** [neonlabsorg/neon-support#22]
**Bug Description**
A clear and concise description of the bug.

**Steps to Reproduce**
1. Go to https://neonpass.live/
2. Click on Connect Wallet
3. Click on "Select a token" 
4. Type "SD" on the research input field
5. wWBTC and wCRV token are listed because the substring SD is contained in the token adresse
...

**Actual Behavior**
![image](https://user-images.githubusercontent.com/103394869/162731301-fb2ce2dc-130b-4cdd-9dab-55f570f9db36.png)

**Expected Behavior**
Only a research on the full adresse string should make the coin appear
![image](https://user-images.githubusercontent.com/103394869/162731383-37911f03-cd9d-442a-996d-991a0b007c49.png)

**Comment by WebKieth** [comment]
on review
https://github.com/neonlabsorg/neon-bridge-ui/pull/86

**Comment by Chaouchinho** [comment]
Hello, thank you for fixing this bug.
It's fixed on my side.
