### ISSUE TITLE
Prefill the amount value when editing source

### ISSUE THREAD

**Issue by Chaouchinho** [neonlabsorg/neon-support#24]
Prefill the amount value when editing source

![image](https://user-images.githubusercontent.com/103394869/163066015-98218b4e-2bbb-4bac-aaa4-b89b4e41b644.png)

![image](https://user-images.githubusercontent.com/103394869/163066036-b758a74c-e973-4ac5-b3a8-168a2473d669.png)

**Comment by gigimon** [comment]
Issue have fixed, pelase check
