### ISSUE TITLE
Impossible to paste value on the amount field

### ISSUE THREAD

**Issue by Chaouchinho** [neonlabsorg/neon-support#25]
Bug Description
It is impossible to paste a value on the amount field

Steps to Reproduce
1. Go to https://neonpass.live/
2. From : Solana / To : Neon
3. Click on Connect Wallet
4. Click on select a token and select a token
5. Try to paste a value in the ammount field

**Actual Behavior**
Impossible to paste
![image](https://user-images.githubusercontent.com/103394869/163066920-6483f562-0f03-4661-b2a0-fd7ba26473ee.png)

**Expected Behavior**
It should be possible to paste an amount

**Comment by gigimon** [comment]
@Chaouchinho hello, we have fixed this and now you could paste value to amount field
