### ISSUE TITLE
Issue when filling amount then disconnecting the wallet

### ISSUE THREAD

**Issue by Chaouchinho** [neonlabsorg/neon-support#26]
**Bug Description**
Issue when filling amount then disconnecting the wallet

Steps to Reproduce
1. Go to https://neonpass.live/
2. From : Neon/ To : Solana
3. Click on Connect Wallet
4. Click on select a token and select a token
5. Enter "10" in the ammount field
6. Unlink the wallet
7. The Next button is still not disabled and you can send 

**Actual Behavior**
![image](https://user-images.githubusercontent.com/103394869/163068882-b69fa0f5-7aba-4990-b78d-caa08b2f32b0.png)
![image](https://user-images.githubusercontent.com/103394869/163068907-c741a610-4bca-40f5-aa87-07da584de88a.png)

**Expected Behavior**
The next button is not disabled after unlinking the wallet

**Comment by WebKieth** [comment]
fixed in https://github.com/neonlabsorg/neon-bridge-ui/pull/91
