### ISSUE TITLE
Undefined and bug when spamming the wallet

### ISSUE THREAD

**Issue by Chaouchinho** [neonlabsorg/neon-support#27]
**Bug Description**
Undefined and bug when spamming the wallet
**Steps to Reproduce**
1. Go to https://neonpass.live/
2. From : Neon/ To : Solana
3. Click on Connect Wallet
4. Spam Disconnect/Connect Wallet

**Actual Behavior**
![image](https://user-images.githubusercontent.com/103394869/163071991-d6c2612b-679b-47e2-a5db-42728220f8e0.png)

**Comment by WebKieth** [comment]
This PR should solve this extra updates for balances. Now refreshes of list and balances is controlling by previous state
https://github.com/neonlabsorg/neon-bridge-ui/pull/93

**Comment by gigimon** [comment]
Issue have fixed, please check
