### ISSUE TITLE
Chainlist requests different URLs for testnet/devnet/mainnet explorers 

### ISSUE THREAD

**Issue by afalaleev** [neonlabsorg/neon-support#30]
**Bug Description**
Neon configuration has a bad link to explorer.
To resolve the issue we open pull request to chainlist repository.
But reviewers requested the different links to explorer for different chains.
https://github.com/ethereum-lists/chains/pull/1113

**Steps to Reproduce**
1. Go to chainlist.org
2. Add configuration of Neon EVM.
3. Try to open link to executed transaction. It will fail with bad link error.
4. Go to PR: https://github.com/ethereum-lists/chains/pull/1113
...

**Actual Behavior**
Currently, it is impossible to set different URLs to neonscan for different chains.

**Expected Behavior**
We should request neonscan to add different URLs for different chains how it works on etherscan:
- Neon Testnet: https://testnet.neonscan.org, https://testnet.explorer.neon-labs.org
- Neon Testnet: https://devnet.neonscan.org, https://devnet.explorer.neon-labs.org
- Neon Testnet: https://mainnet.neonscan.org, https://mainnet.explorer.neon-labs.org

**Additional Context**
https://github.com/ethereum-lists/chains/pull/1113

**Comment by vodolaz** [comment]
redirects done 
testnet.explorer.neon-labs.org -> testnet.neonscan.org
devnet.explorer.neon-labs.org -> devnet.neonscan.org
mainnet.explorer.neon-labs.org -> mainnet.neonscan.org
