### ISSUE TITLE
RPC not working with JsonRpcProvider (ethers js)

### ISSUE THREAD

**Issue by tinhbeng** [neonlabsorg/neon-support#34]
Here is my code being used for testing:

`function getContract(ABI, contractAddress) {`
 ` const url = "https://proxy.devnet.neonlabs.org/solana";`
  `const provider = new ethers.providers.JsonRpcProvider(url);`
 ` return new ethers.Contract(contractAddress, ABI, provider);`
`}`
I called above function to query to node,  it doesn't work ( => timeout). 
Here is my full source code: [Source](https://github.com/tinhbeng/test-etherjs/blob/master/src/App.js)

**Comment by gigimon** [comment]
I think problem resolved.

**Comment by tinhbeng** [comment]
Hi, @gigimon.
Actually I tried the above call before. But it seems that after 5-6 minutes rpc will timeout and return this error:
![Screenshot from 2022-05-30 13-58-48](https://user-images.githubusercontent.com/11867289/170946481-9901d465-e44b-4187-820e-bad378060c60.png)

**Comment by gigimon** [comment]
@tinhbeng show please code or link to repository (if code is opensource)

**Comment by tinhbeng** [comment]
Hi, @gigimon.
My repo: [Source](https://github.com/tinhbeng/test-etherjs/blob/master/src/App.js)

**Comment by gigimon** [comment]
@tinhbeng thx, we have found a problem.

**Comment by gigimon** [comment]
@tinhbeng thx, we have found and fixed problem, Your code work normal! 
![image](https://user-images.githubusercontent.com/297982/171020670-ebeeec8f-dd5b-47d6-8b01-acd39a9ac896.png)

please check

**Comment by tinhbeng** [comment]
Thank @gigimon .
Can you tell me where the problem comes from?. Because before that, I tested it with nodejs and it worked fine. It only occurs this problem when running with reactjs app.

**Comment by gigimon** [comment]
@tinhbeng yes, a problem was in our side in CORS preferences. We changed it and code started work
