### ISSUE TITLE
Issues with adding liquidity pairs on Moraswap

### ISSUE THREAD

**Issue by Venice-Neon** [neonlabsorg/neon-support#35]
Having a problem when adding liquidity pairs for MORA/wETH - MORA/wBTC pairs - transaction on Metamask goes in a loop? i.e. confirmation twice then takes me back to the create pool & supply.
 
Seems like there are issues with MORA & all Wormhole-wrapped tokens in this regard.

Also, normally when you create a pool, you don't have the option to manually select both token amounts, but only one, because it should be perfectly balanced, which is not the case here. So I tried to manually balance the tokens, but that didn't work either.

wDAI works with some and doesn't work with some tokens also.

When I add a liquidity pair, I simply have 2 Metamask tx popping up, then that's it, nothing. (meaning don't really have any meaningful screenshot to take)

**Comment by gigimon** [comment]
I checked this and found 2 problems:
1. transaction size 
2. gas limit very small

![image](https://user-images.githubusercontent.com/297982/173336930-9b558893-b399-4918-ad50-37ed17877f74.png)

**Comment by afalaleev** [comment]
Issue was resolved
