### ISSUE TITLE
Add "MAX" button to Neonpass

### ISSUE THREAD

**Issue by s-medvedev** [neonlabsorg/neon-support#4]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I need to copy and paste my balance to pass ALL tokens through NeonPass

**Describe the solution you'd like**
It will be great to have "MAX" button to specify all tokens that exists on the balance
Also, we can show the current token balance.

**Comment by WebKieth** [comment]
Fixed, deployed, checked on production.
