### ISSUE TITLE
Too high transaction fee (1.7 NEON) for every pass NEON from MetaMask to Solana

### ISSUE THREAD

**Issue by s-medvedev** [neonlabsorg/neon-support#5]
**Bug Description**
User transferring NEON from MM to Phantom.
He gets charged always about 1.7 NEON which is probably too high cause this wasn't just a first-time transfer.

**Steps to Reproduce**
1. Go to https://neonpass.live/
2. Pass NEON from MetaMask to Solana

**Expected Behavior**
Transaction fee lowers then 1.7 NEON for second and next time.

**Actual Behavior**
Transaction fee 1.7 NEON (doesn't depends on the first time or not)

**Comment by valiksinev** [comment]
the problem is not reproduced.
The gas estimation always includes the account creation cost.
But 1.7 Neon is paid only once.
