### ISSUE TITLE
"Processing transaction" screen remains infinitely when sending Neon on NeonPass

### ISSUE THREAD

**Issue by s-medvedev** [neonlabsorg/neon-support#6]
**Bug Description**
While sending Neon for example on Neonpass tokens go through but screen that says "Processing transaction" remains there infinitely.

**Steps to Reproduce**
1. Go to https://neonpass.live
2. Transfer NEON from MM to Phantom

**Expected Behavior**
"Processing transaction" closed when transaction complete

**Actual Behavior**
"Processing transaction" remain infinitely

**Additional Context**
Add any other context about the problem here (screenshots, whether the bug only occurs only in certain mobile/desktop/browser environments, etc.)

**Comment by WebKieth** [comment]
Fixed, deployed, checked on production.
