### ISSUE TITLE
Search bar in our docs doesn't work since we updated website

### ISSUE THREAD

**Issue by s-medvedev** [neonlabsorg/neon-support#8]

**Comment by WebKieth** [comment]
Possible related issue
https://discourse.algolia.com/t/algolia-searchbar-is-not-working-with-docusaurus-v2/14659/2

**Comment by WebKieth** [comment]
yep, this is it
https://github.com/neonlabsorg/neon-evm.docs/pull/173
@YYYurchenko pls allow the commit. Fix is already uploaded on gh-pages

**Comment by WebKieth** [comment]
Search bar is alive but problem is deeper.
We have to connect with algolia support for pages reindex

**Comment by WebKieth** [comment]
So current status of task - freezed. 
@YYYurchenko @zapolnoch - did you write to algolia support?

**Comment by gigimon** [comment]
Problem resolved!
