### ISSUE TITLE
The 10sec betwen request in neonswap.live/#/get-tokens is not realy 10 sec but 60sec

### ISSUE THREAD

**Issue by Chaouchinho** [neonlabsorg/neon-support#9]
**Bug Description**
When trying to add some NEON to my devnet wallet via this WS "https://neonswap.live/neonswap.live/request_airdrop", the time between each request is not configured as 10sec but 60sec

**Steps to Reproduce**
1. Go to https://neonswap.live/#/get-tokens
2. Be sure than your metamask wallet is connected
3. Fill the  "Request test tokens" field with 1000 
4. Click on "Get tokens"
5. Wait betwen 10 and 50 sec and do the exact same thing
6. You will have the error message "Next request will be unlock after **10 seconds** expiration for a security reasons."

...

**Actual Behavior**
The delay between each calls is > 60sec 

**Expected Behavior**

You should be able to add tokens every 10sec

**Additional Context**
I did a python script that show the behavior by waiting 55sec and 65sec betwen each calls.

**### KO with waiting 55 sec**
![image](https://user-images.githubusercontent.com/103394869/162649201-26fdee3c-5c67-4617-8fcb-0c7daa27b76a.png)

**### OK with waiting 65 sec**
![image](https://user-images.githubusercontent.com/103394869/162649356-8e36d68b-e454-4140-bc34-9665cb577573.png)

**Comment by WebKieth** [comment]
Duplicated
https://github.com/neonlabsorg/neon-support/issues/2
